version: '3.1'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:14.7
    container_name: postgres_node
    # 5432로 포워딩 할 경우 host os 에 설치된 postgres와 겹칠 수 있으므로 host에 설치된 postgres를 내려야함.
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    # 실제 postsql을 로컬에서 사용하는게 아니고 도커에서 사용하기 때문에 postgres_data라는 폴더에서 실제 경로를 참조해주게 된다. 
    # 도커 컨테이너를 없애면 안에 정보가 다 없어짐. 볼륨으로 데이터 폴더를 로컬에 두면 컨테이너를 없애도 데이터는 로컬에 들어있음
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
